### PR TITLE
re #2 add value/2

### PR DESCRIPTION
**Pull request by lowks**

### CODE REVIEW

**Comment by moxley** [comment]
Hi @lowks. Thank you for the contribution.

Typically, the bang version of a function raises an exception when there is an error.  Yours does not. I suggest naming this function `value/2` instead.

Also, please indent with two spaces per indent, not four spaces.

Also, please move the function definition to after the `coerce/2` definitions.

**Comment by lowks** [comment]
@moxley I have made the changes and added some tests. Please have a look.

**Comment by moxley** [comment]
Thanks @lowks. Can you make a couple tweaks:
1. Move the function definition out of the private function definitions, to the public section, below the other public functions.
2. Maintain a blank line below and after the function definition.

**Comment by lowks** [comment]
@moxley done.

**Comment by moxley** [comment]
Thanks @lowks!

**Pull request merged**
